- CODE_OF_CONDUCT.md
- README.md
- docs/development.md
- docs/getting-started.md
- docs/oc-install.md
- package.json
- tasks/oc-install/tsconfig.json
> Issue #10 Docs review and update

- package-lock.json
- package.json
> Issue #16 Adding husky + commit-message-validator

- tasks/oc-cmd/src/oc-cmd.ts
- tasks/oc-cmd/src/oc-install.ts
- tasks/oc-cmd/src/task.ts
- tasks/oc-cmd/src/tests/L0.ts
- tasks/oc-cmd/src/tests/L1.ts
- tasks/oc-cmd/src/tests/test-agent-match.ts
- tasks/oc-cmd/src/tests/test-cmd-exec.ts
- tasks/oc-cmd/task.json
- vss-extension.json
> Issue #12 Ensuring AGENT_OS=Linux for oc-cmd task

- .travis.yml
- tasks/oc-cmd/package-lock.json
- tasks/oc-cmd/package.json
- tasks/oc-cmd/src/oc-cmd.ts
- tasks/oc-cmd/src/tests/L0.ts
- tasks/oc-cmd/task.json
- vss-extension.json
> Issue #21 Making sure environment variables get interpolated 

- tasks/oc-cmd/src/oc-install.ts
> Issue #25 Allow authenticated GitHub API request 

- .travis.yml
- package.json
- tasks/oc-cmd/package-lock.json
- tasks/oc-cmd/package.json
- tasks/oc-cmd/src/oc-cmd.ts
- tasks/oc-cmd/src/oc-install.ts
- tasks/oc-cmd/src/task.ts
- tasks/oc-cmd/src/tests/L0.ts
- tasks/oc-cmd/src/tests/L1.ts
- tasks/oc-cmd/src/tests/test-agent-match.ts
- tasks/oc-cmd/src/tests/test-cmd-exec.ts
> Issue #15 Adding dependency to prettier and npm scripts for running it

- README.md
> Issue #36 Adding Azure DevOps badge

- docs/development.md
- package.json
- scripts/vsix-manifest-overrides.json
- tasks/oc-cmd/task.json
- vss-extension.json
> Issue #34 Making changes for publishing under the redhat publisher

- docs/development.md
- docs/getting-started.md
- package-lock.json
- package.json
- src/oc-install.ts
- tasks/config-map/task.json
- tasks/oc-cmd/task.json
- test/oc-install-test.ts
- vss-extension.json
> Issue #50 Allow to specify oc version as fully qualified URL

- azure-pipelines.yml
- docs/development.md
- package.json
- vss-extension.json
> Issue #51 Adding task to set explicit release version

- vss-extension.json
> Issue #57 Adding more meta information to vss-extension.json

- README.md
- docs/details.md
- docs/getting-started.md
- vss-extension.json
> Issue #59 Removing obsolete section from README

- tasks/oc-cmd/task.json
- vss-extension.json
> Issue #63 Marking extension as Preview

- src/oc-run.ts
- tasks/config-map/task.json
- tasks/oc-cmd/task.json
- tasks/oc-setup/task.json
- test/oc-run-test.ts
- vss-extension.json
> Issue #49 Removing leading oc or oc.exe in oc exec task

- CONTRIBUTING.md
- README.md
- docs/details.md
- docs/development.md
- docs/getting-started.md
- package.json
- tasks/config-map/task.json
- tasks/oc-cmd/task.json
- tasks/oc-setup/task.json
- vss-extension.json
> Issue #67 Transfer of repository to redhat-developers

- docs/development.md
> Issue #69 Adding links to CI systems

- docs/getting-started.md
> Issue #76 Adding note about service connection verification

- package.json
- vss-extension.json
> Issue #82 Changing indentation level for extension:version:set

- ci/README.md
- ci/integration.yml
- ci/integration_job_v2.yml
- docs/development.md
> Issue #81 Adding integration test pipeline definition

- docs/getting-started.md
> Issue #86 Adding YAML config to docs

- src/oc-install.ts
> changed way download dir is created (#96)

- Jenkinsfile
Fixes #104
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> Create Jenkins task to publish new version into marketplace

- Jenkinsfile
Fixes #106
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> The Jenkins job is running contineously even no changes are pushed

- package-lock.json
- package.json
removed this as we don't really use this kind of validator in any project and we agreed to use a different commit message format compared to the one described here
> removed commit message validator

- vss-extension.json
> updated version to 1.4.0 (#108)

- src/constants.ts
- src/oc-auth.ts
- test/oc-auth.test.ts
- vss-extension.json
> Added flag for using certificate authority file when connecting to openshift

- CHANGELOG.md
- vss-extension.json
@jeffmaury I tested the extension again after the last merges and it can be published for me. 
Whenever you want you can merge this PR and publish it. Let me know if you have any q.
> Update to 1.4.2

- Jenkinsfile
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> Add Luca to the list of approved releasers

- package-lock.json
- package.json
- src/config-map-task.ts
- src/oc-auth.ts
- src/oc-exec-task.ts
- src/oc-exec.ts
- src/oc-install.ts
- src/oc-setup-task.ts
- test/oc-auth.test.ts
- test/oc-exec.test.ts
- test/oc-install.test.ts
- test/utilStubs.ts
> updated dependencies (#134)

- src/oc-install.ts
> fixed regex to make it work with xx.xx versions (#136)

- README.md
- docs/getting-started.md
> updated documentation for proxy, pipe and redirectors support (#140)

- vss-extension.json
> updated version to 1.5.0 (#141)

- docs/details.md
- docs/getting-started.md
This is related to #149 . Waiting for the proper fix.
> Updated documentation to highlight cURL requirement

- src/oc-condition.ts
- src/oc-conditional-exec-task.ts
- src/oc-exec.ts
- src/oc-install.ts
- src/utils/exec_helper.ts
- tasks/oc-conditional-cmd/task.json
- test/oc-exec.test.ts
- vss-extension.json
PR containing improvements/fixings done while testing new release. It mostly contains better logs/messages displayed so user is aware of what the extension is doing/why it failed
> Fixings/Improvemenets based on tests on version 1.6.0

- src/constants.ts
- src/oc-install.ts
- src/oc-utils.json
- test/oc-install.test.ts
Update oc versions file and fix issue when trying to download v.4 with using major.minor.patch format version
> Updated oc versions file

- docs/getting-started.md
Fixed some visualization errors and incorrect summary
> Fixed documentation

- CHANGELOG.md
- vss-extension.json
> updated version to 1.6.0 (#161)

- README.md
Added section for known issues. It resolves #170
> Added known issues section (#170)

- package-lock.json
- package.json
- src/oc-install.ts
- src/utils/zip_helper.ts
> feat: unzip .tar archive

- Jenkinsfile
Signed-off-by: Luca Stocchi <lstocchi@redhat.com>
> chore: update Jenkins to rhel 8

- Jenkinsfile
Signed-off-by: Luca Stocchi <lstocchi@redhat.com>
> chore: fix sftp
